[unix_http_server]
file=/tmp/simnet-transcriber-supervisor.sock
chmod=0700

[supervisord]
logfile=/tmp/simnet-transcriber-supervisord.log
pidfile=/tmp/simnet-transcriber-supervisord.pid
childlogdir=/tmp
nodaemon=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/simnet-transcriber-supervisor.sock

[include]
files = /workspace/simnet-transcriber/simnet-transcriber.conf
